# Generated by Django 5.0.1 on 2024-01-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeria", "0007_fotografia_usuario"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fotografia",
            name="publica",
            field=models.BooleanField(default=True),
        ),
    ]
