# Generated by Django 5.0.1 on 2024-01-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeria", "0002_alter_fotografia_legenda"),
    ]

    operations = [
        migrations.AddField(
            model_name="fotografia",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("ESTRELA", "Estrela"),
                    ("NEBULOSA", "Nebulosa"),
                    ("PLANETA", "Planeta"),
                    ("PLANETA ANAO", "Planeta Anao"),
                    ("COMETA", "Cometa"),
                ],
                default="",
                max_length=100,
            ),
        ),
    ]
