# Generated by Django 5.0.1 on 2024-01-11 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeria", "0003_fotografia_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="fotografia",
            name="publica",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="fotografia",
            name="categoria",
            field=models.CharField(
                choices=[
                    ("ESTRELA", "Estrela"),
                    ("NEBULOSA", "Nebulosa"),
                    ("PLANETA", "Planeta"),
                    ("PLANETA ANAO", "Planeta Anao"),
                    ("COMETA", "Cometa"),
                    ("GALAXIA", "Galaxia"),
                ],
                default="",
                max_length=100,
            ),
        ),
    ]
