# Generated by Django 5.0.1 on 2024-01-11 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeria", "0004_fotografia_publica_alter_fotografia_categoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="fotografia",
            name="data_publica",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
